### ISSUE TITLE
getting below error for npm run dev

### ISSUE THREAD

**Issue by animeesh** [Evavic44/victoreke.com#53]
function checkValue<T>(value: T | undefined, errorMsg: string): T {
  23 |   if (value === undefined) {
> 24 |     throw new Error(`Missing Environment Variable: ${errorMsg}`);
     |          ^
  25 |   }
  26 |   return value;
  27 | }

**Comment by Evavic44** [comment]
Thanks for raising this issue, @animeesh. I've updated the README with a more descriptive guide on how to run the project locally. Do have a look. :)
