### ISSUE TITLE
Resume File Type

### ISSUE THREAD

**Issue by The-CodeINN** [Evavic44/victoreke.com#57]
The resume downloaded is not showing as a pdf

**Comment by The-CodeINN** [comment]
I don't want to open a pull request, by adding .pdf to the href fixes the issue.
` 
<a
href={`${data.resumeURL}?dl=${data.fullName}-resume.pdf`}
>
 .....
</a>
`

**Comment by Evavic44** [comment]
Thanks for reporting this issue. ⚡

**Comment by Evavic44** [comment]
Turns out the issue was coming from the CDN. Download works now.
