### ISSUE TITLE
Wanted to know, how you added the followed animation?

### ISSUE THREAD

**Issue by pranjal-barnwal** [Evavic44/victoreke.com#82]
Hi Victoreke,

I'm building my blow from scratch and I want to implement the below animation of grid lines, like you used in your portfolio.
![image](https://github.com/Evavic44/victoreke.com/assets/71400605/759de085-a050-4615-891d-6863a7996c18)

Can you please tell me which library you used or how to implement it?
I tried copying it but it remained static

**Comment by Evavic44** [comment]
I didn't use any library, it's plain CSS. You can find the code [here](https://github.com/Evavic44/victoreke.com/blob/f7055a4e49cd805216838a0d55d38e37e7a1195d/app/styles/globals.css#L24-L36)

**Comment by egomaragustaf** [comment]
Hello Victoreke! Can you tell me how to find or create that svg hero?

**Comment by pranjal-barnwal** [comment]
Thank you so much @Evavic44  for your help.
I was building a [blog page](https://pranjalkumar.in), and I needed it here.

![https://pranjalkumar.in](https://github.com/Evavic44/victoreke.com/assets/71400605/a2fbf0ce-8c5b-4aa1-be00-3c93c169d13b)
