### ISSUE TITLE
Usage Part - How to do it?

### ISSUE THREAD

**Issue by aamargant** [Evavic44/victoreke.com#83]
Hello,

First thanks for providing this project open-source.

I want to know how did you do the Usage part where you have all the technologies, how did you do the list with the image and the name of the tool, could you provide an example please, did you do it through the studio?

Thanks in advance

**Comment by Evavic44** [comment]
The links are added via Sanity studio. I'm simply attaching the favicon of every link added as an image. Here's the [PortableText component](https://github.com/Evavic44/victoreke.com/blob/main/app/components/shared/CustomPortableTextFavicon.tsx).

The code for the image is generated using this [favicon component](https://github.com/Evavic44/victoreke.com/blob/main/app/utils/favicon.tsx)

**Comment by Evavic44** [comment]
> [!Note]
> If you don't want to use a token, comment it out in the [env.api.ts][env-api] file or else it will throw errors.
