### ISSUE TITLE
Incorrect Breakpoint Prefix in HeroSvg Component

### ISSUE THREAD

**Issue by wanfahdiva** [Evavic44/victoreke.com#87]
I'd like to report a potential issue with the breakpoint prefix used in the `HeroSvg` component.

* **Issue:** The current class name `lg:w-[450px] lgl:h-[450px]` appears to have an incorrect breakpoint prefix `lgl`.
* **Expected:** Based on Tailwind CSS conventions, the correct prefix for a larger screen size breakpoint is likely `lg`.
* **Potential Fix:** To achieve the intended behavior, consider replacing `lgl` with `lg` in the class name:

```tsx
className="lg:w-[450px] lg:h-[450px] w-full h-full"

**Comment by Evavic44** [comment]
Thanks for the report. Feel free to send a PR if you have the time.
