### ISSUE TITLE
Unable to clone and run locally

### ISSUE THREAD

**Issue by AMGOcyber123** [Evavic44/victoreke.com#89]
I have tried cloning and running the entire project locally and facing serious of issues and despite setting the ACCESS_TOKEN I still am not able to run the project and during, npm run dev , I face a "Dynamic Routes Conflict" error and get this error as well 

```
Error: You cannot use different slug names for the same dynamic path ('index' !== 'tool').
```

**Comment by Evavic44** [comment]
This error isn't related to a missing environment variables so I'm not exactly sure what's happening. Try creating a fork of the project and reproduce the error so I can look at it.

**Comment by AMGOcyber123** [comment]
I'll try to test it again and let you know

**Comment by jaswanth-0821** [comment]
getting same error ,how did you fixed it

**Comment by Evavic44** [comment]
Anyone going through this issue, create a reproducible repository so I can test it.

**Comment by junwai7159** [comment]
My workaround is deleting the folder studio/[[...tools]]
