### ISSUE TITLE
empty studio

### ISSUE THREAD

**Issue by jaswanth-0821** [Evavic44/victoreke.com#90]
why my studio is empty? i filled all the variables ,but when i check http://localhost:3000/studio this it giving empty page.

**Comment by Evavic44** [comment]
Please elaborate. What does "empty page" mean? Attach screenshots and console output if possible

**Comment by jaswanth-0821** [comment]
When i direct to studio i am not getting any options to fill ,i am getting blank page
here are the attachments

![image](https://github.com/Evavic44/victoreke.com/assets/77910115/74b5b32a-e37c-4bac-a729-bf54e4e62914)
![image](https://github.com/Evavic44/victoreke.com/assets/77910115/4f6b72d8-81a6-4639-b024-abcde51e116c)

**Comment by Evavic44** [comment]
Run the build command and paste the output here. Also open the console to check for any errors as well. Paste them both here

**Comment by jaswanth-0821** [comment]
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.5.0

YOUR TYPESCRIPT VERSION: 5.5.2

Please only submit bug reports when using the officially supported version.

=============
✔ No ESLint warnings or errors
  ▲ Next.js 14.2.4
  - Environments: .env.local, .env

   Creating an optimized production build ...
request to https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap failed, reason: 

Retrying 1/3...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
 ✓ Generating static pages (15/15)
 ✓ Collecting build traces
 ✓ Finalizing page optimization

Route (app)                              Size     First Load JS
┌ ○ /                                    53.3 kB         188 kB
├ ○ /_not-found                          879 B          88.9 kB
├ ○ /about                               3.56 kB         141 kB
├ ƒ /api/revalidate                      0 B                0 B
├ ○ /apple-icon-12o0cb.png               0 B                0 B
├ ○ /blog                                527 B           140 kB
├ ƒ /blog/[post]                         13.1 kB         155 kB
├ ○ /icon1-12o0cb.png                    0 B                0 B
├ ○ /icon2-12o0cb.png                    0 B                0 B
├ ○ /icon3-12o0cb.png                    0 B                0 B
├ ○ /icon4-12o0cb.png                    0 B                0 B
├ ○ /photos                              490 B           128 kB
├ ○ /projects                            2.01 kB         137 kB
├ ƒ /projects/[project]                  2.01 kB         137 kB
└ ƒ /studio/[[...index]]                 1.11 MB         1.2 MB
+ First Load JS shared by all            88 kB
  ├ chunks/7023-554e79fb9c3c11f8.js      31.7 kB
  ├ chunks/fd9d1056-97717795e1a7ef4e.js  53.6 kB
  └ other shared chunks (total)          2.65 kB


○  (Static)   prerendered as static content
ƒ  (Dynamic)  server-rendered on demand

**Comment by jaswanth-0821** [comment]
sorry , I found the error in the console and it is because of i didnt comment links like NEXT_PUBLIC_GISCUS_REPOID....once i commented those it is working fine for me.

**Comment by Evavic44** [comment]
I was referring to the browser console, not the editor terminal. I suspect you have some mismatching environment variables. Check if you copied the proper variables from your project on [Sanity.io/manage](https://sanity.io/manage)
